channels:
- conda-forge
dependencies:
- python=3.10.18
- pip<=25.1
- pip:
  - mlflow==3.2.0
  - cloudpickle==3.1.1
  - numpy==2.2.6
  - pandas==2.3.1
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.15.2
name: mlflow-env
